package com.yokdil.vocab.utils

import com.yokdil.vocab.data.db.entities.Word

object WordSeedData {

    fun getWords(): List<Word> = listOf(
        // ==================== A ====================
        Word(word = "aberrant", turkishMeaning = "anormal, sapkın", partOfSpeech = "adj",
            synonyms = "[\"abnormal\",\"deviant\",\"anomalous\"]", antonyms = "[\"normal\",\"typical\"]",
            exampleSentence = "The aberrant behavior of the particles puzzled physicists.",
            exampleTranslation = "Parçacıkların anormal davranışı fizikçileri şaşırttı.", category = "fen", difficulty = 3, examYear = "2019"),
        Word(word = "abiotic", turkishMeaning = "cansız, abiyotik", partOfSpeech = "adj",
            synonyms = "[\"non-living\",\"inorganic\"]", antonyms = "[\"biotic\",\"living\"]",
            exampleSentence = "Temperature and light are abiotic factors in an ecosystem.",
            exampleTranslation = "Sıcaklık ve ışık bir ekosistemdeki abiyotik faktörlerdir.", category = "fen", difficulty = 2, examYear = "2020"),
        Word(word = "absorption", turkishMeaning = "emilim, soğurma", partOfSpeech = "noun",
            synonyms = "[\"assimilation\",\"uptake\",\"incorporation\"]", antonyms = "[\"emission\",\"release\",\"excretion\"]",
            exampleSentence = "The absorption of nutrients occurs mainly in the small intestine.",
            exampleTranslation = "Besin emilimi esas olarak ince bağırsakta gerçekleşir.", category = "fen", difficulty = 2, examYear = "2018"),
        Word(word = "abundance", turkishMeaning = "bolluk, çokluk", partOfSpeech = "noun",
            synonyms = "[\"plenty\",\"profusion\",\"plethora\"]", antonyms = "[\"scarcity\",\"shortage\",\"dearth\"]",
            exampleSentence = "The abundance of carbon in organic molecules is remarkable.",
            exampleTranslation = "Organik moleküllerdeki karbon bolluğu dikkat çekicidir.", category = "fen", difficulty = 2, examYear = "2021"),
        Word(word = "accelerate", turkishMeaning = "hızlandırmak", partOfSpeech = "verb",
            synonyms = "[\"expedite\",\"hasten\",\"speed up\"]", antonyms = "[\"decelerate\",\"slow down\",\"retard\"]",
            exampleSentence = "Catalysts accelerate chemical reactions without being consumed.",
            exampleTranslation = "Katalizörler, tüketilmeksizin kimyasal reaksiyonları hızlandırır.", category = "fen", difficulty = 2, examYear = "2017"),
        Word(word = "accumulate", turkishMeaning = "birikmek, yığılmak", partOfSpeech = "verb",
            synonyms = "[\"amass\",\"gather\",\"stockpile\"]", antonyms = "[\"disperse\",\"dissipate\",\"scatter\"]",
            exampleSentence = "Toxins can accumulate in the fatty tissues of organisms.",
            exampleTranslation = "Toksinler organizmaların yağ dokularında birikebilir.", category = "fen", difficulty = 2, examYear = "2019"),
        Word(word = "acidic", turkishMeaning = "asidik, asit niteliğinde", partOfSpeech = "adj",
            synonyms = "[\"sour\",\"corrosive\",\"acerbic\"]", antonyms = "[\"alkaline\",\"basic\",\"neutral\"]",
            exampleSentence = "Acidic soil can inhibit the growth of certain plant species.",
            exampleTranslation = "Asidik toprak bazı bitki türlerinin büyümesini engelleyebilir.", category = "fen", difficulty = 2, examYear = "2020"),
        Word(word = "adaptation", turkishMeaning = "uyum, adaptasyon", partOfSpeech = "noun",
            synonyms = "[\"adjustment\",\"modification\",\"acclimatization\"]", antonyms = "[\"maladaptation\",\"incompatibility\"]",
            exampleSentence = "Thick fur is an adaptation of arctic animals to cold climates.",
            exampleTranslation = "Kalın kürk, Arktik hayvanların soğuk iklimlere uyumudur.", category = "fen", difficulty = 2, examYear = "2018"),
        Word(word = "adhere", turkishMeaning = "yapışmak, bağlı kalmak", partOfSpeech = "verb",
            synonyms = "[\"stick\",\"cling\",\"bond\"]", antonyms = "[\"detach\",\"separate\",\"loosen\"]",
            exampleSentence = "Cells adhere to surfaces using specific receptor proteins.",
            exampleTranslation = "Hücreler, belirli reseptör proteinleri kullanarak yüzeylere yapışır.", category = "fen", difficulty = 2, examYear = "2021"),
        Word(word = "adverse", turkishMeaning = "olumsuz, zararlı", partOfSpeech = "adj",
            synonyms = "[\"detrimental\",\"harmful\",\"unfavorable\"]", antonyms = "[\"beneficial\",\"favorable\",\"advantageous\"]",
            exampleSentence = "Adverse weather conditions delayed the scientific expedition.",
            exampleTranslation = "Olumsuz hava koşulları bilimsel seferi geciktirdi.", category = "fen", difficulty = 2, examYear = "2022"),
        Word(word = "aggregate", turkishMeaning = "toplamak, bir araya getirmek / toplam", partOfSpeech = "verb/noun",
            synonyms = "[\"collect\",\"accumulate\",\"compile\"]", antonyms = "[\"disperse\",\"scatter\",\"separate\"]",
            exampleSentence = "Data from multiple experiments were aggregated for analysis.",
            exampleTranslation = "Birden fazla deneyin verileri analiz için bir araya getirildi.", category = "fen", difficulty = 3, examYear = "2020"),
        Word(word = "algorithm", turkishMeaning = "algoritma", partOfSpeech = "noun",
            synonyms = "[\"procedure\",\"method\",\"protocol\"]", antonyms = "[\"randomness\",\"disorder\"]",
            exampleSentence = "The algorithm predicts protein folding with high accuracy.",
            exampleTranslation = "Algoritma, protein katlanmasını yüksek doğrulukla tahmin eder.", category = "fen", difficulty = 3, examYear = "2021"),
        Word(word = "alleviate", turkishMeaning = "hafifletmek, azaltmak", partOfSpeech = "verb",
            synonyms = "[\"relieve\",\"mitigate\",\"ease\"]", antonyms = "[\"aggravate\",\"worsen\",\"intensify\"]",
            exampleSentence = "The new drug alleviates symptoms without causing side effects.",
            exampleTranslation = "Yeni ilaç yan etki yaratmadan semptomları hafifletir.", category = "fen", difficulty = 2, examYear = "2019"),
        Word(word = "alteration", turkishMeaning = "değişiklik, değişim", partOfSpeech = "noun",
            synonyms = "[\"modification\",\"change\",\"transformation\"]", antonyms = "[\"preservation\",\"stability\",\"constancy\"]",
            exampleSentence = "A slight alteration in temperature can affect enzyme activity.",
            exampleTranslation = "Sıcaklıktaki küçük bir değişiklik enzim aktivitesini etkileyebilir.", category = "fen", difficulty = 2, examYear = "2018"),
        Word(word = "ambiguous", turkishMeaning = "belirsiz, muğlak", partOfSpeech = "adj",
            synonyms = "[\"unclear\",\"vague\",\"equivocal\"]", antonyms = "[\"clear\",\"unambiguous\",\"definite\"]",
            exampleSentence = "The experimental results were ambiguous and required further testing.",
            exampleTranslation = "Deneysel sonuçlar belirsizdi ve daha fazla test gerektiriyordu.", category = "fen", difficulty = 3, examYear = "2020"),
        Word(word = "anaerobic", turkishMeaning = "anaerobik, oksijensiz", partOfSpeech = "adj",
            synonyms = "[\"oxygen-free\",\"without oxygen\"]", antonyms = "[\"aerobic\",\"oxygen-dependent\"]",
            exampleSentence = "Anaerobic bacteria thrive in environments devoid of oxygen.",
            exampleTranslation = "Anaerobik bakteriler oksijensiz ortamlarda gelişir.", category = "fen", difficulty = 2, examYear = "2017"),
        Word(word = "analogous", turkishMeaning = "benzer, analojik", partOfSpeech = "adj",
            synonyms = "[\"similar\",\"comparable\",\"parallel\"]", antonyms = "[\"different\",\"dissimilar\",\"contrasting\"]",
            exampleSentence = "The wing of a bat is analogous to the fin of a fish.",
            exampleTranslation = "Bir yarasa kanadı, bir balık yüzgecine benzerdir.", category = "fen", difficulty = 3, examYear = "2021"),
        Word(word = "anomaly", turkishMeaning = "anormallik, sapma", partOfSpeech = "noun",
            synonyms = "[\"irregularity\",\"deviation\",\"aberration\"]", antonyms = "[\"norm\",\"regularity\",\"standard\"]",
            exampleSentence = "Scientists detected an anomaly in the magnetic field of the planet.",
            exampleTranslation = "Bilim insanları gezegenin manyetik alanında bir anormallik tespit etti.", category = "fen", difficulty = 3, examYear = "2022"),
        Word(word = "antagonist", turkishMeaning = "antagonist, rakip, zıt etki gösteren", partOfSpeech = "noun",
            synonyms = "[\"opponent\",\"rival\",\"inhibitor\"]", antonyms = "[\"agonist\",\"promoter\",\"ally\"]",
            exampleSentence = "This compound acts as an antagonist to the receptor protein.",
            exampleTranslation = "Bu bileşik reseptör proteinine karşı antagonist olarak işlev görür.", category = "fen", difficulty = 3, examYear = "2019"),
        Word(word = "apparent", turkishMeaning = "görünür, belirgin, açık", partOfSpeech = "adj",
            synonyms = "[\"evident\",\"obvious\",\"visible\"]", antonyms = "[\"hidden\",\"obscure\",\"concealed\"]",
            exampleSentence = "There is no apparent correlation between the two variables.",
            exampleTranslation = "İki değişken arasında görünür bir korelasyon yoktur.", category = "fen", difficulty = 2, examYear = "2018"),
        // ==================== B ====================
        Word(word = "biosphere", turkishMeaning = "biyosfer", partOfSpeech = "noun",
            synonyms = "[\"ecosphere\",\"living world\"]", antonyms = "[\"abiosphere\",\"non-living environment\"]",
            exampleSentence = "The biosphere encompasses all living organisms on Earth.",
            exampleTranslation = "Biyosfer, Dünya'daki tüm canlı organizmaları kapsar.", category = "fen", difficulty = 2, examYear = "2020"),
        Word(word = "biodiversity", turkishMeaning = "biyoçeşitlilik", partOfSpeech = "noun",
            synonyms = "[\"biological diversity\",\"species variety\"]", antonyms = "[\"monoculture\",\"uniformity\"]",
            exampleSentence = "Tropical rainforests contain the greatest biodiversity on Earth.",
            exampleTranslation = "Tropikal yağmur ormanları, Dünya'da en büyük biyoçeşitliliği barındırır.", category = "fen", difficulty = 2, examYear = "2019"),
        Word(word = "buffer", turkishMeaning = "tampon, tampon çözeltisi", partOfSpeech = "noun/verb",
            synonyms = "[\"cushion\",\"stabilizer\",\"moderator\"]", antonyms = "[\"destabilizer\",\"irritant\"]",
            exampleSentence = "Blood contains a natural buffer system to maintain pH balance.",
            exampleTranslation = "Kan, pH dengesini korumak için doğal bir tampon sistemi içerir.", category = "fen", difficulty = 3, examYear = "2021"),
        Word(word = "byproduct", turkishMeaning = "yan ürün", partOfSpeech = "noun",
            synonyms = "[\"secondary product\",\"spinoff\",\"residue\"]", antonyms = "[\"primary product\",\"main product\"]",
            exampleSentence = "Carbon dioxide is a byproduct of cellular respiration.",
            exampleTranslation = "Karbondioksit, hücresel solunumun bir yan ürünüdür.", category = "fen", difficulty = 2, examYear = "2018"),
        Word(word = "benign", turkishMeaning = "iyi huylu, zararsız", partOfSpeech = "adj",
            synonyms = "[\"harmless\",\"non-malignant\",\"mild\"]", antonyms = "[\"malignant\",\"harmful\",\"dangerous\"]",
            exampleSentence = "The tumor was benign and did not require surgical removal.",
            exampleTranslation = "Tümör iyi huyluydu ve cerrahi müdahale gerektirmiyordu.", category = "fen", difficulty = 2, examYear = "2020"),
        // ==================== C ====================
        Word(word = "catalyst", turkishMeaning = "katalizör", partOfSpeech = "noun",
            synonyms = "[\"accelerator\",\"promoter\",\"facilitator\"]", antonyms = "[\"inhibitor\",\"retardant\",\"suppressor\"]",
            exampleSentence = "Enzymes act as biological catalysts in metabolic reactions.",
            exampleTranslation = "Enzimler, metabolik reaksiyonlarda biyolojik katalizör olarak işlev görür.", category = "fen", difficulty = 2, examYear = "2017"),
        Word(word = "cell membrane", turkishMeaning = "hücre zarı", partOfSpeech = "noun",
            synonyms = "[\"plasma membrane\",\"phospholipid bilayer\"]", antonyms = "[\"cell wall\",\"extracellular matrix\"]",
            exampleSentence = "The cell membrane regulates the passage of substances in and out of the cell.",
            exampleTranslation = "Hücre zarı, maddelerin hücreye giriş çıkışını düzenler.", category = "fen", difficulty = 2, examYear = "2018"),
        Word(word = "chromosome", turkishMeaning = "kromozom", partOfSpeech = "noun",
            synonyms = "[\"DNA strand\",\"genetic material\",\"chromatid\"]", antonyms = "[\"plasmid\",\"mitochondrial DNA\"]",
            exampleSentence = "Humans have 46 chromosomes organized in 23 pairs.",
            exampleTranslation = "İnsanlar 23 çift halinde organize edilmiş 46 kromozoma sahiptir.", category = "fen", difficulty = 2, examYear = "2019"),
        Word(word = "cohesion", turkishMeaning = "kohezyon, uyum, birleşme", partOfSpeech = "noun",
            synonyms = "[\"adhesion\",\"unity\",\"bonding\"]", antonyms = "[\"separation\",\"fragmentation\",\"discord\"]",
            exampleSentence = "Water's cohesion allows it to form droplets on surfaces.",
            exampleTranslation = "Suyun kohezyonu, yüzeylerde damlacıklar oluşturmasına izin verir.", category = "fen", difficulty = 3, examYear = "2021"),
        Word(word = "compound", turkishMeaning = "bileşik, bileşen", partOfSpeech = "noun/adj",
            synonyms = "[\"mixture\",\"composite\",\"combination\"]", antonyms = "[\"element\",\"pure substance\",\"simple\"]",
            exampleSentence = "Water is a compound made of hydrogen and oxygen atoms.",
            exampleTranslation = "Su, hidrojen ve oksijen atomlarından oluşan bir bileşiktir.", category = "fen", difficulty = 2, examYear = "2017"),
        Word(word = "conduction", turkishMeaning = "iletim, kondüksiyon", partOfSpeech = "noun",
            synonyms = "[\"transmission\",\"transfer\",\"propagation\"]", antonyms = "[\"insulation\",\"resistance\",\"blocking\"]",
            exampleSentence = "Heat conduction in metals occurs through free electron movement.",
            exampleTranslation = "Metallerde ısı iletimi, serbest elektron hareketi yoluyla gerçekleşir.", category = "fen", difficulty = 2, examYear = "2020"),
        Word(word = "conservation", turkishMeaning = "koruma, muhafaza", partOfSpeech = "noun",
            synonyms = "[\"preservation\",\"protection\",\"maintenance\"]", antonyms = "[\"destruction\",\"degradation\",\"waste\"]",
            exampleSentence = "Conservation of energy is a fundamental principle in physics.",
            exampleTranslation = "Enerjinin korunumu, fizikte temel bir ilkedir.", category = "fen", difficulty = 2, examYear = "2018"),
        Word(word = "contaminant", turkishMeaning = "kirletici, bulaşıcı madde", partOfSpeech = "noun",
            synonyms = "[\"pollutant\",\"impurity\",\"toxin\"]", antonyms = "[\"purifier\",\"cleaner\",\"purifier\"]",
            exampleSentence = "Industrial waste introduced heavy metal contaminants into the river.",
            exampleTranslation = "Endüstriyel atık nehre ağır metal kirleticiler soktu.", category = "fen", difficulty = 2, examYear = "2022"),
        Word(word = "correlation", turkishMeaning = "korelasyon, ilişki", partOfSpeech = "noun",
            synonyms = "[\"relationship\",\"association\",\"connection\"]", antonyms = "[\"independence\",\"unrelated\",\"disconnection\"]",
            exampleSentence = "Researchers found a strong correlation between sleep and memory.",
            exampleTranslation = "Araştırmacılar uyku ve bellek arasında güçlü bir korelasyon buldu.", category = "fen", difficulty = 2, examYear = "2019"),
        Word(word = "covalent", turkishMeaning = "kovalent, ortaklaşa", partOfSpeech = "adj",
            synonyms = "[\"shared bond\",\"molecular bond\"]", antonyms = "[\"ionic\",\"metallic\",\"hydrogen bond\"]",
            exampleSentence = "Covalent bonds are formed by sharing electron pairs between atoms.",
            exampleTranslation = "Kovalent bağlar, atomlar arasında elektron çiftlerinin paylaşılmasıyla oluşur.", category = "fen", difficulty = 3, examYear = "2021"),
        Word(word = "cytoplasm", turkishMeaning = "sitoplazma", partOfSpeech = "noun",
            synonyms = "[\"cell fluid\",\"intracellular fluid\",\"protoplasm\"]", antonyms = "[\"extracellular fluid\",\"nucleus\"]",
            exampleSentence = "Many metabolic reactions occur in the cytoplasm of the cell.",
            exampleTranslation = "Pek çok metabolik reaksiyon hücrenin sitoplazmasında gerçekleşir.", category = "fen", difficulty = 2, examYear = "2018"),
        // ==================== D ====================
        Word(word = "decompose", turkishMeaning = "ayrışmak, çürümek", partOfSpeech = "verb",
            synonyms = "[\"decay\",\"rot\",\"break down\"]", antonyms = "[\"synthesize\",\"compose\",\"form\"]",
            exampleSentence = "Bacteria decompose organic matter into simpler substances.",
            exampleTranslation = "Bakteriler organik maddeyi daha basit maddelere ayrıştırır.", category = "fen", difficulty = 2, examYear = "2019"),
        Word(word = "deficiency", turkishMeaning = "eksiklik, yetersizlik", partOfSpeech = "noun",
            synonyms = "[\"lack\",\"shortage\",\"insufficiency\"]", antonyms = "[\"abundance\",\"surplus\",\"excess\"]",
            exampleSentence = "Vitamin D deficiency can lead to weakened bones.",
            exampleTranslation = "D vitamini eksikliği zayıf kemiklere yol açabilir.", category = "fen", difficulty = 2, examYear = "2020"),
        Word(word = "degenerate", turkishMeaning = "dejenerasyona uğramak, bozulmak", partOfSpeech = "verb/adj",
            synonyms = "[\"deteriorate\",\"decay\",\"decline\"]", antonyms = "[\"regenerate\",\"improve\",\"evolve\"]",
            exampleSentence = "Without regular exercise, muscle tissue can degenerate.",
            exampleTranslation = "Düzenli egzersiz olmadan kas dokusu bozulabilir.", category = "fen", difficulty = 3, examYear = "2021"),
        Word(word = "density", turkishMeaning = "yoğunluk", partOfSpeech = "noun",
            synonyms = "[\"compactness\",\"concentration\",\"thickness\"]", antonyms = "[\"sparsity\",\"rarity\",\"thinness\"]",
            exampleSentence = "The density of water increases as temperature decreases.",
            exampleTranslation = "Suyun yoğunluğu sıcaklık azaldıkça artar.", category = "fen", difficulty = 2, examYear = "2017"),
        Word(word = "differentiation", turkishMeaning = "farklılaşma, ayrışım", partOfSpeech = "noun",
            synonyms = "[\"specialization\",\"distinction\",\"divergence\"]", antonyms = "[\"dedifferentiation\",\"similarity\",\"uniformity\"]",
            exampleSentence = "Cell differentiation allows stem cells to become specialized tissues.",
            exampleTranslation = "Hücre farklılaşması, kök hücrelerin özelleşmiş dokulara dönüşmesine izin verir.", category = "fen", difficulty = 3, examYear = "2022"),
        Word(word = "diffusion", turkishMeaning = "difüzyon, yayılma", partOfSpeech = "noun",
            synonyms = "[\"spreading\",\"dispersion\",\"osmosis\"]", antonyms = "[\"concentration\",\"accumulation\",\"convergence\"]",
            exampleSentence = "Oxygen enters cells through diffusion across the membrane.",
            exampleTranslation = "Oksijen, zardan difüzyon yoluyla hücrelere girer.", category = "fen", difficulty = 2, examYear = "2018"),
        Word(word = "disperse", turkishMeaning = "dağılmak, yaymak", partOfSpeech = "verb",
            synonyms = "[\"scatter\",\"spread\",\"disseminate\"]", antonyms = "[\"concentrate\",\"gather\",\"accumulate\"]",
            exampleSentence = "Wind disperses seeds over large distances.",
            exampleTranslation = "Rüzgar tohumları geniş mesafelere dağıtır.", category = "fen", difficulty = 2, examYear = "2019"),
        Word(word = "dominance", turkishMeaning = "baskınlık, dominanslık", partOfSpeech = "noun",
            synonyms = "[\"superiority\",\"prevalence\",\"dominion\"]", antonyms = "[\"recessiveness\",\"submission\",\"inferiority\"]",
            exampleSentence = "Genetic dominance determines which traits are expressed in offspring.",
            exampleTranslation = "Genetik baskınlık, yavrularda hangi özelliklerin ifade edileceğini belirler.", category = "fen", difficulty = 3, examYear = "2020"),
        // ==================== E ====================
        Word(word = "ecosystem", turkishMeaning = "ekosistem", partOfSpeech = "noun",
            synonyms = "[\"ecological system\",\"biome\",\"habitat\"]", antonyms = "[\"artificial environment\",\"monoculture\"]",
            exampleSentence = "A coral reef ecosystem supports thousands of marine species.",
            exampleTranslation = "Bir mercan resifi ekosistemi binlerce deniz türünü destekler.", category = "fen", difficulty = 2, examYear = "2017"),
        Word(word = "electromagnetic", turkishMeaning = "elektromanyetik", partOfSpeech = "adj",
            synonyms = "[\"magnetic-electric\",\"radiative\",\"photonic\"]", antonyms = "[\"non-radiative\",\"static\"]",
            exampleSentence = "Electromagnetic radiation includes visible light and X-rays.",
            exampleTranslation = "Elektromanyetik radyasyon görünür ışık ve X-ışınlarını içerir.", category = "fen", difficulty = 2, examYear = "2021"),
        Word(word = "embryo", turkishMeaning = "embriyo, cenin", partOfSpeech = "noun",
            synonyms = "[\"fetus\",\"developing organism\",\"zygote stage\"]", antonyms = "[\"adult organism\",\"mature organism\"]",
            exampleSentence = "The embryo develops through a series of cell divisions.",
            exampleTranslation = "Embriyo bir dizi hücre bölünmesi yoluyla gelişir.", category = "fen", difficulty = 2, examYear = "2018"),
        Word(word = "empirical", turkishMeaning = "ampirik, deneysel", partOfSpeech = "adj",
            synonyms = "[\"observational\",\"experimental\",\"evidence-based\"]", antonyms = "[\"theoretical\",\"speculative\",\"abstract\"]",
            exampleSentence = "Empirical evidence is essential to validate scientific hypotheses.",
            exampleTranslation = "Ampirik kanıt, bilimsel hipotezleri doğrulamak için gereklidir.", category = "fen", difficulty = 3, examYear = "2022"),
        Word(word = "enzyme", turkishMeaning = "enzim", partOfSpeech = "noun",
            synonyms = "[\"catalyst\",\"biocatalyst\",\"protein catalyst\"]", antonyms = "[\"inhibitor\",\"antienzyme\"]",
            exampleSentence = "Each enzyme is specific to a particular biochemical reaction.",
            exampleTranslation = "Her enzim belirli bir biyokimyasal reaksiyona özgüdür.", category = "fen", difficulty = 2, examYear = "2017"),
        Word(word = "equilibrium", turkishMeaning = "denge, denge durumu", partOfSpeech = "noun",
            synonyms = "[\"balance\",\"stability\",\"homeostasis\"]", antonyms = "[\"imbalance\",\"instability\",\"disequilibrium\"]",
            exampleSentence = "Chemical equilibrium is reached when reaction rates are equal.",
            exampleTranslation = "Kimyasal denge, reaksiyon hızları eşit olduğunda ulaşılır.", category = "fen", difficulty = 2, examYear = "2019"),
        Word(word = "erosion", turkishMeaning = "erozyon, aşınma", partOfSpeech = "noun",
            synonyms = "[\"weathering\",\"corrosion\",\"attrition\"]", antonyms = "[\"deposition\",\"accumulation\",\"building up\"]",
            exampleSentence = "Soil erosion degrades the fertility of agricultural land.",
            exampleTranslation = "Toprak erozyonu tarım arazilerinin verimliliğini azaltır.", category = "fen", difficulty = 2, examYear = "2018"),
        Word(word = "evaporation", turkishMeaning = "buharlaşma", partOfSpeech = "noun",
            synonyms = "[\"vaporization\",\"volatilization\",\"drying\"]", antonyms = "[\"condensation\",\"liquefaction\",\"precipitation\"]",
            exampleSentence = "Evaporation from leaves drives water movement in plants.",
            exampleTranslation = "Yapraklardan buharlaşma, bitkilerde su hareketini sağlar.", category = "fen", difficulty = 2, examYear = "2020"),
        Word(word = "evolution", turkishMeaning = "evrim", partOfSpeech = "noun",
            synonyms = "[\"development\",\"progression\",\"natural selection\"]", antonyms = "[\"devolution\",\"regression\",\"stagnation\"]",
            exampleSentence = "Evolution explains the diversity of life through natural selection.",
            exampleTranslation = "Evrim, doğal seçilim yoluyla yaşamın çeşitliliğini açıklar.", category = "fen", difficulty = 2, examYear = "2017"),
        Word(word = "excrete", turkishMeaning = "atmak, dışarı sürmek", partOfSpeech = "verb",
            synonyms = "[\"eliminate\",\"expel\",\"discharge\"]", antonyms = "[\"absorb\",\"retain\",\"store\"]",
            exampleSentence = "Kidneys excrete waste products from the blood.",
            exampleTranslation = "Böbrekler, kandan atık ürünleri dışarı atar.", category = "fen", difficulty = 2, examYear = "2021"),
        // ==================== F ====================
        Word(word = "fermentation", turkishMeaning = "fermantasyon, mayalanma", partOfSpeech = "noun",
            synonyms = "[\"anaerobic respiration\",\"ferment\",\"yeast activity\"]", antonyms = "[\"aerobic respiration\",\"oxidation\"]",
            exampleSentence = "Fermentation converts glucose to alcohol in the absence of oxygen.",
            exampleTranslation = "Fermantasyon, oksijen yokluğunda glikozu alkole dönüştürür.", category = "fen", difficulty = 2, examYear = "2019"),
        Word(word = "flux", turkishMeaning = "akış, sürekli değişim", partOfSpeech = "noun",
            synonyms = "[\"flow\",\"fluctuation\",\"variation\"]", antonyms = "[\"stability\",\"constancy\",\"equilibrium\"]",
            exampleSentence = "The flux of energy through an ecosystem drives food webs.",
            exampleTranslation = "Bir ekosistem içindeki enerji akışı besin ağlarını harekete geçirir.", category = "fen", difficulty = 3, examYear = "2022"),
        Word(word = "fossil", turkishMeaning = "fosil", partOfSpeech = "noun",
            synonyms = "[\"remnant\",\"relic\",\"petrified remains\"]", antonyms = "[\"living organism\",\"fresh specimen\"]",
            exampleSentence = "Fossils provide evidence of organisms that lived millions of years ago.",
            exampleTranslation = "Fosiller, milyonlarca yıl önce yaşamış organizmalar hakkında kanıt sağlar.", category = "fen", difficulty = 2, examYear = "2018"),
        Word(word = "frequency", turkishMeaning = "frekans, sıklık", partOfSpeech = "noun",
            synonyms = "[\"rate\",\"recurrence\",\"periodicity\"]", antonyms = "[\"rarity\",\"infrequency\",\"scarcity\"]",
            exampleSentence = "High-frequency sound waves are used in medical ultrasound.",
            exampleTranslation = "Yüksek frekanslı ses dalgaları tıbbi ultrason amaçlı kullanılır.", category = "fen", difficulty = 2, examYear = "2020"),
        // ==================== G ====================
        Word(word = "gene", turkishMeaning = "gen", partOfSpeech = "noun",
            synonyms = "[\"hereditary unit\",\"DNA sequence\",\"allele\"]", antonyms = "[\"non-coding region\",\"junk DNA\"]",
            exampleSentence = "A single gene may code for multiple proteins through splicing.",
            exampleTranslation = "Tek bir gen, ayıklama yoluyla birden fazla protein için kodlayabilir.", category = "fen", difficulty = 2, examYear = "2018"),
        Word(word = "genotype", turkishMeaning = "genotip", partOfSpeech = "noun",
            synonyms = "[\"genetic makeup\",\"genetic composition\",\"DNA profile\"]", antonyms = "[\"phenotype\",\"expressed traits\"]",
            exampleSentence = "An organism's genotype determines its potential characteristics.",
            exampleTranslation = "Bir organizmanın genotipi, potansiyel özelliklerini belirler.", category = "fen", difficulty = 3, examYear = "2020"),
        Word(word = "gravity", turkishMeaning = "yerçekimi, ağırlık", partOfSpeech = "noun",
            synonyms = "[\"gravitation\",\"attraction\",\"pull\"]", antonyms = "[\"repulsion\",\"levitation\",\"buoyancy\"]",
            exampleSentence = "Gravity is the force that keeps planets in orbit around the sun.",
            exampleTranslation = "Yerçekimi, gezegenleri güneş etrafındaki yörüngede tutan kuvvettir.", category = "fen", difficulty = 2, examYear = "2017"),
        // ==================== H ====================
        Word(word = "habitat", turkishMeaning = "habitat, yaşam ortamı", partOfSpeech = "noun",
            synonyms = "[\"environment\",\"ecosystem\",\"dwelling\"]", antonyms = "[\"artificial environment\",\"foreign territory\"]",
            exampleSentence = "Deforestation destroys the natural habitat of many species.",
            exampleTranslation = "Ormansızlaşma birçok türün doğal habitatını yok eder.", category = "fen", difficulty = 2, examYear = "2019"),
        Word(word = "hereditary", turkishMeaning = "kalıtsal, soydan geçen", partOfSpeech = "adj",
            synonyms = "[\"genetic\",\"inherited\",\"congenital\"]", antonyms = "[\"acquired\",\"environmental\",\"learned\"]",
            exampleSentence = "Some diseases are hereditary and can be passed from parent to child.",
            exampleTranslation = "Bazı hastalıklar kalıtsaldır ve ebeveynden çocuğa geçebilir.", category = "fen", difficulty = 2, examYear = "2018"),
        Word(word = "homeostasis", turkishMeaning = "homeostazi, iç denge", partOfSpeech = "noun",
            synonyms = "[\"equilibrium\",\"self-regulation\",\"stability\"]", antonyms = "[\"disequilibrium\",\"disruption\",\"imbalance\"]",
            exampleSentence = "The body maintains homeostasis through hormonal feedback systems.",
            exampleTranslation = "Vücut, hormonal geri bildirim sistemleri aracılığıyla homeostazisi korur.", category = "fen", difficulty = 3, examYear = "2021"),
        Word(word = "hypothesis", turkishMeaning = "hipotez, varsayım", partOfSpeech = "noun",
            synonyms = "[\"assumption\",\"theory\",\"supposition\"]", antonyms = "[\"fact\",\"proof\",\"certainty\"]",
            exampleSentence = "The hypothesis was supported by repeated experimental evidence.",
            exampleTranslation = "Hipotez, tekrarlanan deneysel kanıtlarla desteklendi.", category = "fen", difficulty = 2, examYear = "2022"),
        // ==================== I ====================
        Word(word = "immutable", turkishMeaning = "değişmez, sabit", partOfSpeech = "adj",
            synonyms = "[\"unchangeable\",\"fixed\",\"invariable\"]", antonyms = "[\"mutable\",\"variable\",\"changeable\"]",
            exampleSentence = "The speed of light is considered an immutable physical constant.",
            exampleTranslation = "Işık hızı, değişmez bir fiziksel sabit olarak kabul edilir.", category = "fen", difficulty = 3, examYear = "2021"),
        Word(word = "impermeable", turkishMeaning = "geçirimsiz, geçirgen olmayan", partOfSpeech = "adj",
            synonyms = "[\"impervious\",\"non-porous\",\"waterproof\"]", antonyms = "[\"permeable\",\"porous\",\"penetrable\"]",
            exampleSentence = "Cell membranes are impermeable to large polar molecules.",
            exampleTranslation = "Hücre zarları büyük polar moleküllere karşı geçirimsizdir.", category = "fen", difficulty = 3, examYear = "2020"),
        Word(word = "incubate", turkishMeaning = "kuluçkaya yatmak, inkübe etmek", partOfSpeech = "verb",
            synonyms = "[\"hatch\",\"nurture\",\"cultivate\"]", antonyms = "[\"neglect\",\"cool\",\"abandon\"]",
            exampleSentence = "Bacteria are incubated at 37°C to mimic body temperature.",
            exampleTranslation = "Bakteriler, vücut sıcaklığını taklit etmek için 37°C'de inkübe edilir.", category = "fen", difficulty = 2, examYear = "2019"),
        Word(word = "inert", turkishMeaning = "inert, tepkimsiz, atıl", partOfSpeech = "adj",
            synonyms = "[\"unreactive\",\"inactive\",\"stable\"]", antonyms = "[\"reactive\",\"active\",\"volatile\"]",
            exampleSentence = "Noble gases such as helium are chemically inert.",
            exampleTranslation = "Helyum gibi soy gazlar kimyasal açıdan inert (tepkimsiz) tir.", category = "fen", difficulty = 3, examYear = "2022"),
        Word(word = "inference", turkishMeaning = "çıkarım, sonuç çıkarma", partOfSpeech = "noun",
            synonyms = "[\"deduction\",\"conclusion\",\"reasoning\"]", antonyms = "[\"assumption\",\"speculation\",\"guess\"]",
            exampleSentence = "Scientists made an inference about climate change from ice core data.",
            exampleTranslation = "Bilim insanları buz çekirdeği verilerinden iklim değişikliği hakkında çıkarım yaptı.", category = "fen", difficulty = 3, examYear = "2021"),
        Word(word = "inhibit", turkishMeaning = "engellemek, bastırmak", partOfSpeech = "verb",
            synonyms = "[\"suppress\",\"restrain\",\"hinder\"]", antonyms = "[\"promote\",\"stimulate\",\"activate\"]",
            exampleSentence = "Certain chemicals can inhibit enzyme activity in cells.",
            exampleTranslation = "Bazı kimyasallar hücrelerde enzim aktivitesini engelleyebilir.", category = "fen", difficulty = 2, examYear = "2018"),
        Word(word = "instability", turkishMeaning = "kararsızlık, istikrarsızlık", partOfSpeech = "noun",
            synonyms = "[\"volatility\",\"irregularity\",\"turbulence\"]", antonyms = "[\"stability\",\"constancy\",\"equilibrium\"]",
            exampleSentence = "Genetic instability can lead to mutations and cancer.",
            exampleTranslation = "Genetik kararsızlık mutasyonlara ve kansere yol açabilir.", category = "fen", difficulty = 2, examYear = "2020"),
        Word(word = "integral", turkishMeaning = "temel, ayrılmaz, integral", partOfSpeech = "adj/noun",
            synonyms = "[\"essential\",\"fundamental\",\"core\"]", antonyms = "[\"peripheral\",\"optional\",\"secondary\"]",
            exampleSentence = "Mitochondria are integral components of eukaryotic cells.",
            exampleTranslation = "Mitokondri, ökaryotik hücrelerin ayrılmaz bileşenleridir.", category = "fen", difficulty = 3, examYear = "2022"),
        // ==================== L ====================
        Word(word = "lethal", turkishMeaning = "ölümcül, öldürücü", partOfSpeech = "adj",
            synonyms = "[\"fatal\",\"deadly\",\"mortal\"]", antonyms = "[\"harmless\",\"benign\",\"non-toxic\"]",
            exampleSentence = "Exposure to high radiation doses can be lethal to humans.",
            exampleTranslation = "Yüksek radyasyon dozlarına maruz kalmak insanlar için ölümcül olabilir.", category = "fen", difficulty = 2, examYear = "2019"),
        Word(word = "luminescent", turkishMeaning = "biyolüminesan, ışık yayan", partOfSpeech = "adj",
            synonyms = "[\"glowing\",\"fluorescent\",\"phosphorescent\"]", antonyms = "[\"dark\",\"opaque\",\"non-emitting\"]",
            exampleSentence = "Some deep-sea organisms are luminescent to attract prey.",
            exampleTranslation = "Bazı derin deniz organizmaları avlarını çekmek için ışık yayar.", category = "fen", difficulty = 3, examYear = "2021"),
        // ==================== M ====================
        Word(word = "magnitude", turkishMeaning = "büyüklük, şiddet", partOfSpeech = "noun",
            synonyms = "[\"size\",\"scale\",\"extent\"]", antonyms = "[\"smallness\",\"insignificance\",\"minuteness\"]",
            exampleSentence = "The magnitude of an earthquake is measured on the Richter scale.",
            exampleTranslation = "Bir depremin büyüklüğü Richter ölçeğiyle ölçülür.", category = "fen", difficulty = 2, examYear = "2018"),
        Word(word = "malignant", turkishMeaning = "malign, kötü huylu (kanser)", partOfSpeech = "adj",
            synonyms = "[\"cancerous\",\"harmful\",\"deadly\"]", antonyms = "[\"benign\",\"harmless\",\"non-cancerous\"]",
            exampleSentence = "Malignant tumors can spread to surrounding tissues.",
            exampleTranslation = "Kötü huylu tümörler çevre dokulara yayılabilir.", category = "fen", difficulty = 2, examYear = "2020"),
        Word(word = "mechanism", turkishMeaning = "mekanizma, işleyiş", partOfSpeech = "noun",
            synonyms = "[\"process\",\"system\",\"method\"]", antonyms = "[\"randomness\",\"disorder\",\"chaos\"]",
            exampleSentence = "Scientists discovered the molecular mechanism behind DNA repair.",
            exampleTranslation = "Bilim insanları DNA onarımının arkasındaki moleküler mekanizmayı keşfetti.", category = "fen", difficulty = 2, examYear = "2017"),
        Word(word = "membrane", turkishMeaning = "zar, membran", partOfSpeech = "noun",
            synonyms = "[\"layer\",\"film\",\"barrier\"]", antonyms = "[\"opening\",\"gap\",\"hole\"]",
            exampleSentence = "The nuclear membrane separates the nucleus from the cytoplasm.",
            exampleTranslation = "Çekirdek zarı, çekirdeği sitoplazmadan ayırır.", category = "fen", difficulty = 2, examYear = "2019"),
        Word(word = "metabolism", turkishMeaning = "metabolizma", partOfSpeech = "noun",
            synonyms = "[\"biochemical processes\",\"catabolism\",\"anabolism\"]", antonyms = "[\"inactivity\",\"dormancy\",\"stasis\"]",
            exampleSentence = "Aerobic exercise increases the rate of metabolism.",
            exampleTranslation = "Aerobik egzersiz metabolizma hızını artırır.", category = "fen", difficulty = 2, examYear = "2018"),
        Word(word = "mitosis", turkishMeaning = "mitoz (hücre bölünmesi)", partOfSpeech = "noun",
            synonyms = "[\"cell division\",\"somatic division\"]", antonyms = "[\"meiosis\",\"cell death\",\"apoptosis\"]",
            exampleSentence = "Mitosis produces two identical daughter cells.",
            exampleTranslation = "Mitoz iki özdeş yavru hücre üretir.", category = "fen", difficulty = 2, examYear = "2021"),
        Word(word = "molecule", turkishMeaning = "molekül", partOfSpeech = "noun",
            synonyms = "[\"compound\",\"chemical unit\",\"atom cluster\"]", antonyms = "[\"atom\",\"ion\",\"element\"]",
            exampleSentence = "A DNA molecule carries genetic information in the form of base sequences.",
            exampleTranslation = "Bir DNA molekülü, baz dizileri biçiminde genetik bilgi taşır.", category = "fen", difficulty = 2, examYear = "2017"),
        Word(word = "mutation", turkishMeaning = "mutasyon, genetik değişim", partOfSpeech = "noun",
            synonyms = "[\"genetic change\",\"variation\",\"alteration\"]", antonyms = "[\"conservation\",\"wild type\",\"stability\"]",
            exampleSentence = "A single mutation in a gene can cause a hereditary disease.",
            exampleTranslation = "Bir gendeki tek bir mutasyon kalıtsal hastalığa neden olabilir.", category = "fen", difficulty = 2, examYear = "2020"),
        // ==================== N ====================
        Word(word = "neuron", turkishMeaning = "nöron, sinir hücresi", partOfSpeech = "noun",
            synonyms = "[\"nerve cell\",\"neural cell\"]", antonyms = "[\"glial cell\",\"non-neural cell\"]",
            exampleSentence = "A single neuron can form thousands of synaptic connections.",
            exampleTranslation = "Tek bir nöron binlerce sinaptik bağlantı oluşturabilir.", category = "fen", difficulty = 2, examYear = "2018"),
        Word(word = "nucleus", turkishMeaning = "çekirdek, nükleus", partOfSpeech = "noun",
            synonyms = "[\"core\",\"center\",\"command center\"]", antonyms = "[\"cytoplasm\",\"periphery\",\"exterior\"]",
            exampleSentence = "The nucleus contains the cell's genetic material.",
            exampleTranslation = "Çekirdek, hücrenin genetik materyalini içerir.", category = "fen", difficulty = 2, examYear = "2017"),
        // ==================== O ====================
        Word(word = "osmosis", turkishMeaning = "ozmoz", partOfSpeech = "noun",
            synonyms = "[\"water diffusion\",\"passive transport\"]", antonyms = "[\"active transport\",\"pumping\"]",
            exampleSentence = "Osmosis allows water to move from low to high solute concentration.",
            exampleTranslation = "Ozmoz, suyun düşük çözünen konsantrasyonundan yüksek olana doğru hareket etmesini sağlar.", category = "fen", difficulty = 2, examYear = "2019"),
        Word(word = "oxidation", turkishMeaning = "oksidasyon, yükseltgenme", partOfSpeech = "noun",
            synonyms = "[\"combustion\",\"burning\",\"corrosion\"]", antonyms = "[\"reduction\",\"gaining electrons\"]",
            exampleSentence = "Oxidation of iron produces rust over time.",
            exampleTranslation = "Demirin oksidasyonu zamanla pas oluşturur.", category = "fen", difficulty = 2, examYear = "2020"),
        // ==================== P ====================
        Word(word = "pathogen", turkishMeaning = "patojen, hastalık etkeni", partOfSpeech = "noun",
            synonyms = "[\"microbe\",\"germ\",\"infectious agent\"]", antonyms = "[\"probiotic\",\"beneficial microbe\",\"symbiont\"]",
            exampleSentence = "The pathogen spread rapidly through the population.",
            exampleTranslation = "Patojen popülasyon içinde hızla yayıldı.", category = "fen", difficulty = 2, examYear = "2018"),
        Word(word = "permeability", turkishMeaning = "geçirgenlik", partOfSpeech = "noun",
            synonyms = "[\"porosity\",\"penetrability\",\"diffusivity\"]", antonyms = "[\"impermeability\",\"resistance\",\"blockage\"]",
            exampleSentence = "Membrane permeability is controlled by protein channels.",
            exampleTranslation = "Zar geçirgenliği, protein kanalları tarafından kontrol edilir.", category = "fen", difficulty = 3, examYear = "2021"),
        Word(word = "phenotype", turkishMeaning = "fenotip, gözlemlenebilir özellikler", partOfSpeech = "noun",
            synonyms = "[\"observable traits\",\"expressed characteristics\"]", antonyms = "[\"genotype\",\"genetic makeup\"]",
            exampleSentence = "Eye color is a phenotype determined by multiple genes.",
            exampleTranslation = "Göz rengi birden fazla gen tarafından belirlenen bir fenotiptir.", category = "fen", difficulty = 3, examYear = "2020"),
        Word(word = "photosynthesis", turkishMeaning = "fotosentez", partOfSpeech = "noun",
            synonyms = "[\"carbon fixation\",\"light reaction\",\"autotrophic nutrition\"]", antonyms = "[\"respiration\",\"chemosynthesis\"]",
            exampleSentence = "Photosynthesis converts light energy into chemical energy.",
            exampleTranslation = "Fotosentez, ışık enerjisini kimyasal enerjiye dönüştürür.", category = "fen", difficulty = 2, examYear = "2017"),
        Word(word = "polymer", turkishMeaning = "polimer", partOfSpeech = "noun",
            synonyms = "[\"macromolecule\",\"chain molecule\",\"polymerized compound\"]", antonyms = "[\"monomer\",\"small molecule\"]",
            exampleSentence = "DNA is a natural polymer composed of nucleotide monomers.",
            exampleTranslation = "DNA, nükleotid monomerlerinden oluşan doğal bir polimerdir.", category = "fen", difficulty = 3, examYear = "2022"),
        Word(word = "precipitation", turkishMeaning = "çökelme, yağış", partOfSpeech = "noun",
            synonyms = "[\"rainfall\",\"sedimentation\",\"condensation\"]", antonyms = "[\"evaporation\",\"dissolution\",\"sublimation\"]",
            exampleSentence = "Acid precipitation damages soil and aquatic ecosystems.",
            exampleTranslation = "Asit yağışı toprağa ve sucul ekosistemlere zarar verir.", category = "fen", difficulty = 2, examYear = "2019"),
        Word(word = "proliferate", turkishMeaning = "çoğalmak, hızla yayılmak", partOfSpeech = "verb",
            synonyms = "[\"multiply\",\"reproduce\",\"spread\"]", antonyms = "[\"decrease\",\"diminish\",\"decline\"]",
            exampleSentence = "Cancer cells proliferate rapidly and invade surrounding tissues.",
            exampleTranslation = "Kanser hücreleri hızla çoğalır ve çevre dokulara invazyon yapar.", category = "fen", difficulty = 3, examYear = "2021"),
        Word(word = "protein", turkishMeaning = "protein", partOfSpeech = "noun",
            synonyms = "[\"polypeptide\",\"macromolecule\",\"amino acid chain\"]", antonyms = "[\"lipid\",\"carbohydrate\",\"nucleic acid\"]",
            exampleSentence = "Proteins perform structural and functional roles in living cells.",
            exampleTranslation = "Proteinler canlı hücrelerde yapısal ve işlevsel rol oynar.", category = "fen", difficulty = 2, examYear = "2017"),
        // ==================== Q ====================
        Word(word = "quantitative", turkishMeaning = "niceliksel, sayısal", partOfSpeech = "adj",
            synonyms = "[\"measurable\",\"numerical\",\"statistical\"]", antonyms = "[\"qualitative\",\"descriptive\",\"subjective\"]",
            exampleSentence = "Quantitative analysis provides measurable data for scientific studies.",
            exampleTranslation = "Niceliksel analiz, bilimsel çalışmalar için ölçülebilir veri sağlar.", category = "fen", difficulty = 3, examYear = "2022"),
        // ==================== R ====================
        Word(word = "radiation", turkishMeaning = "radyasyon, ışıma", partOfSpeech = "noun",
            synonyms = "[\"emission\",\"rays\",\"energy waves\"]", antonyms = "[\"absorption\",\"shielding\",\"blocking\"]",
            exampleSentence = "Ionizing radiation can damage the DNA in cells.",
            exampleTranslation = "İyonlaştırıcı radyasyon hücrelerdeki DNA'ya zarar verebilir.", category = "fen", difficulty = 2, examYear = "2019"),
        Word(word = "receptor", turkishMeaning = "reseptör, almaç", partOfSpeech = "noun",
            synonyms = "[\"binding site\",\"sensor\",\"ligand binder\"]", antonyms = "[\"effector\",\"transmitter\"]",
            exampleSentence = "Hormone receptors on the cell membrane trigger cellular responses.",
            exampleTranslation = "Hücre zarındaki hormon reseptörleri hücresel yanıtları tetikler.", category = "fen", difficulty = 2, examYear = "2018"),
        Word(word = "regenerate", turkishMeaning = "yenilenmek, rejenerasyon", partOfSpeech = "verb",
            synonyms = "[\"renew\",\"restore\",\"regrow\"]", antonyms = "[\"degenerate\",\"deteriorate\",\"decay\"]",
            exampleSentence = "Liver cells can regenerate after partial removal of the liver.",
            exampleTranslation = "Karaciğer hücreleri, karaciğerin kısmen çıkarılmasının ardından yenilenebilir.", category = "fen", difficulty = 2, examYear = "2020"),
        Word(word = "replicate", turkishMeaning = "kopyalamak, çoğaltmak", partOfSpeech = "verb",
            synonyms = "[\"copy\",\"duplicate\",\"reproduce\"]", antonyms = "[\"destroy\",\"eliminate\",\"mutate\"]",
            exampleSentence = "Viruses replicate inside host cells to produce new copies.",
            exampleTranslation = "Virüsler, yeni kopyalar üretmek için konak hücrelerin içinde çoğalır.", category = "fen", difficulty = 2, examYear = "2021"),
        Word(word = "resistance", turkishMeaning = "direnç, direnme", partOfSpeech = "noun",
            synonyms = "[\"immunity\",\"tolerance\",\"opposition\"]", antonyms = "[\"susceptibility\",\"sensitivity\",\"vulnerability\"]",
            exampleSentence = "Antibiotic resistance is a growing threat to public health.",
            exampleTranslation = "Antibiyotik direnci kamu sağlığına yönelik artan bir tehdittir.", category = "fen", difficulty = 2, examYear = "2022"),
        // ==================== S ====================
        Word(word = "sediment", turkishMeaning = "tortu, çökelti, sediman", partOfSpeech = "noun",
            synonyms = "[\"deposit\",\"residue\",\"silt\"]", antonyms = "[\"solution\",\"dissolved substance\"]",
            exampleSentence = "Sediment layers in rock reveal information about past environments.",
            exampleTranslation = "Kayaçtaki tortu katmanları geçmiş ortamlar hakkında bilgi verir.", category = "fen", difficulty = 2, examYear = "2018"),
        Word(word = "soluble", turkishMeaning = "çözünür, eriyebilir", partOfSpeech = "adj",
            synonyms = "[\"dissolvable\",\"miscible\",\"dilutable\"]", antonyms = "[\"insoluble\",\"immiscible\",\"undissolvable\"]",
            exampleSentence = "Many vitamins are fat-soluble rather than water-soluble.",
            exampleTranslation = "Birçok vitamin suda değil yağda çözünür.", category = "fen", difficulty = 2, examYear = "2019"),
        Word(word = "species", turkishMeaning = "tür, cins", partOfSpeech = "noun",
            synonyms = "[\"taxon\",\"group\",\"kind\"]", antonyms = "[\"genus\",\"family\",\"kingdom\"]",
            exampleSentence = "A new species of deep-sea fish was discovered last year.",
            exampleTranslation = "Geçen yıl yeni bir derin deniz balığı türü keşfedildi.", category = "fen", difficulty = 2, examYear = "2020"),
        Word(word = "stimulus", turkishMeaning = "uyaran, stimülüs", partOfSpeech = "noun",
            synonyms = "[\"trigger\",\"signal\",\"prompt\"]", antonyms = "[\"inhibitor\",\"suppressor\",\"dampener\"]",
            exampleSentence = "The organism responded to the light stimulus by turning toward it.",
            exampleTranslation = "Organizma, ışık uyaranına dönerek tepki verdi.", category = "fen", difficulty = 2, examYear = "2017"),
        Word(word = "substrate", turkishMeaning = "substrat, alt tabaka", partOfSpeech = "noun",
            synonyms = "[\"reactant\",\"base material\",\"medium\"]", antonyms = "[\"product\",\"enzyme\",\"catalyst\"]",
            exampleSentence = "The substrate binds to the active site of the enzyme.",
            exampleTranslation = "Substrat, enzimin aktif bölgesine bağlanır.", category = "fen", difficulty = 3, examYear = "2021"),
        Word(word = "synthesis", turkishMeaning = "sentez", partOfSpeech = "noun",
            synonyms = "[\"production\",\"formation\",\"assembly\"]", antonyms = "[\"decomposition\",\"breakdown\",\"catabolism\"]",
            exampleSentence = "Protein synthesis occurs in the ribosomes of the cell.",
            exampleTranslation = "Protein sentezi hücrenin ribozomlarında gerçekleşir.", category = "fen", difficulty = 2, examYear = "2018"),
        // ==================== T ====================
        Word(word = "taxonomy", turkishMeaning = "taksonomi, sınıflandırma bilimi", partOfSpeech = "noun",
            synonyms = "[\"classification\",\"systematics\",\"nomenclature\"]", antonyms = "[\"disorder\",\"ambiguity\",\"randomness\"]",
            exampleSentence = "Modern taxonomy uses genetic data to classify organisms.",
            exampleTranslation = "Modern taksonomi, organizmaları sınıflandırmak için genetik verileri kullanır.", category = "fen", difficulty = 3, examYear = "2022"),
        Word(word = "temperature", turkishMeaning = "sıcaklık", partOfSpeech = "noun",
            synonyms = "[\"heat level\",\"thermal state\",\"degree\"]", antonyms = "[\"cold\",\"freeze\",\"absolute zero\"]",
            exampleSentence = "Temperature is a key variable in chemical reaction rates.",
            exampleTranslation = "Sıcaklık, kimyasal reaksiyon hızlarında temel bir değişkendir.", category = "fen", difficulty = 2, examYear = "2017"),
        Word(word = "toxin", turkishMeaning = "toksin, zehir", partOfSpeech = "noun",
            synonyms = "[\"poison\",\"venom\",\"contaminant\"]", antonyms = "[\"antidote\",\"antitoxin\",\"cure\"]",
            exampleSentence = "Certain bacteria release toxins that damage the nervous system.",
            exampleTranslation = "Bazı bakteriler sinir sistemine zarar veren toksinler salgılar.", category = "fen", difficulty = 2, examYear = "2019"),
        Word(word = "trait", turkishMeaning = "özellik, karakter", partOfSpeech = "noun",
            synonyms = "[\"characteristic\",\"feature\",\"attribute\"]", antonyms = "[\"defect\",\"absence\",\"lack\"]",
            exampleSentence = "Height is a polygenic trait influenced by many genes.",
            exampleTranslation = "Boy, birçok gen tarafından etkilenen poligenik bir özelliktir.", category = "fen", difficulty = 2, examYear = "2020"),
        Word(word = "transcription", turkishMeaning = "transkripsiyon, kopyalama", partOfSpeech = "noun",
            synonyms = "[\"copying\",\"RNA synthesis\",\"gene expression\"]", antonyms = "[\"translation\",\"silencing\",\"repression\"]",
            exampleSentence = "Transcription converts DNA information into RNA.",
            exampleTranslation = "Transkripsiyon, DNA bilgisini RNA'ya dönüştürür.", category = "fen", difficulty = 3, examYear = "2021"),
        Word(word = "translocation", turkishMeaning = "yer değiştirme, translokasyon", partOfSpeech = "noun",
            synonyms = "[\"transfer\",\"movement\",\"transport\"]", antonyms = "[\"fixation\",\"retention\",\"immobility\"]",
            exampleSentence = "Chromosomal translocation can result in abnormal gene expression.",
            exampleTranslation = "Kromozomal translokasyon anormal gen ekspresyonuna yol açabilir.", category = "fen", difficulty = 3, examYear = "2022"),
        // ==================== U ====================
        Word(word = "ultraviolet", turkishMeaning = "ultraviyole, mor ötesi", partOfSpeech = "adj",
            synonyms = "[\"UV radiation\",\"short-wave light\"]", antonyms = "[\"infrared\",\"visible light\"]",
            exampleSentence = "Ultraviolet radiation from the sun can cause DNA damage.",
            exampleTranslation = "Güneşten gelen ultraviyole radyasyon DNA hasarına neden olabilir.", category = "fen", difficulty = 2, examYear = "2018"),
        Word(word = "uncertainty", turkishMeaning = "belirsizlik, kesin olmama", partOfSpeech = "noun",
            synonyms = "[\"doubt\",\"ambiguity\",\"unpredictability\"]", antonyms = "[\"certainty\",\"precision\",\"accuracy\"]",
            exampleSentence = "The Heisenberg uncertainty principle limits knowledge of particle position.",
            exampleTranslation = "Heisenberg belirsizlik ilkesi, parçacık konumuna ilişkin bilgiyi sınırlandırır.", category = "fen", difficulty = 3, examYear = "2021"),
        // ==================== V ====================
        Word(word = "variable", turkishMeaning = "değişken", partOfSpeech = "noun/adj",
            synonyms = "[\"factor\",\"parameter\",\"variant\"]", antonyms = "[\"constant\",\"fixed\",\"invariable\"]",
            exampleSentence = "In the experiment, temperature was the independent variable.",
            exampleTranslation = "Deneyde sıcaklık bağımsız değişkendi.", category = "fen", difficulty = 2, examYear = "2017"),
        Word(word = "velocity", turkishMeaning = "hız, sürat", partOfSpeech = "noun",
            synonyms = "[\"speed\",\"pace\",\"swiftness\"]", antonyms = "[\"stillness\",\"stagnation\",\"inertia\"]",
            exampleSentence = "The velocity of a moving object changes when a force is applied.",
            exampleTranslation = "Hareket eden bir nesnenin hızı, bir kuvvet uygulandığında değişir.", category = "fen", difficulty = 2, examYear = "2019"),
        Word(word = "viable", turkishMeaning = "yaşayabilir, uygulanabilir", partOfSpeech = "adj",
            synonyms = "[\"survivable\",\"feasible\",\"practicable\"]", antonyms = "[\"nonviable\",\"impossible\",\"unfeasible\"]",
            exampleSentence = "Only viable seeds will germinate under proper conditions.",
            exampleTranslation = "Yalnızca yaşayabilir tohumlar uygun koşullar altında filizlenir.", category = "fen", difficulty = 2, examYear = "2020"),
        Word(word = "viscosity", turkishMeaning = "viskozite, akışkanlık direnci", partOfSpeech = "noun",
            synonyms = "[\"thickness\",\"resistance to flow\",\"stickiness\"]", antonyms = "[\"fluidity\",\"low resistance\",\"thinness\"]",
            exampleSentence = "Blood viscosity affects the rate of blood flow in vessels.",
            exampleTranslation = "Kan viskozitesi, damarlar içindeki kan akış hızını etkiler.", category = "fen", difficulty = 3, examYear = "2022"),
        // ==================== W ====================
        Word(word = "wavelength", turkishMeaning = "dalga boyu", partOfSpeech = "noun",
            synonyms = "[\"wave length\",\"frequency interval\",\"period\"]", antonyms = "[\"frequency\",\"amplitude\",\"intensity\"]",
            exampleSentence = "Different wavelengths of light correspond to different colors.",
            exampleTranslation = "Farklı dalga boyları farklı renklere karşılık gelir.", category = "fen", difficulty = 2, examYear = "2018"),
        // ==================== EXTRA SCIENCE TERMS ====================
        Word(word = "allele", turkishMeaning = "alel, gen varyantı", partOfSpeech = "noun",
            synonyms = "[\"gene variant\",\"hereditary form\",\"alternative gene\"]", antonyms = "[\"wild type\",\"dominant allele\"]",
            exampleSentence = "Each parent contributes one allele for each gene.",
            exampleTranslation = "Her ebeveyn her gen için bir alel katkısında bulunur.", category = "fen", difficulty = 3, examYear = "2021"),
        Word(word = "amino acid", turkishMeaning = "amino asit", partOfSpeech = "noun",
            synonyms = "[\"protein building block\",\"peptide unit\",\"organic compound\"]", antonyms = "[\"fatty acid\",\"nucleotide\"]",
            exampleSentence = "Twenty amino acids combine to form all proteins in living organisms.",
            exampleTranslation = "Yirmi amino asit bir araya gelerek canlılardaki tüm proteinleri oluşturur.", category = "fen", difficulty = 2, examYear = "2019"),
        Word(word = "apex predator", turkishMeaning = "tepe avcısı", partOfSpeech = "noun",
            synonyms = "[\"top predator\",\"keystone predator\"]", antonyms = "[\"prey\",\"herbivore\"]",
            exampleSentence = "Sharks are apex predators in marine ecosystems.",
            exampleTranslation = "Köpekbalıkları, deniz ekosistemlerinin tepe avcılarıdır.", category = "fen", difficulty = 2, examYear = "2020"),
        Word(word = "aquifer", turkishMeaning = "akifer, yer altı su kaynağı", partOfSpeech = "noun",
            synonyms = "[\"groundwater reservoir\",\"water-bearing rock\"]", antonyms = "[\"impermeable layer\",\"aquitard\"]",
            exampleSentence = "Many cities rely on aquifers for their drinking water supply.",
            exampleTranslation = "Birçok şehir, içme suyu temini için akiferlere güvenmektedir.", category = "fen", difficulty = 3, examYear = "2022"),
        Word(word = "arteriosclerosis", turkishMeaning = "arterioskleroz, damar sertliği", partOfSpeech = "noun",
            synonyms = "[\"hardening of arteries\",\"atherosclerosis\"]", antonyms = "[\"healthy arteries\",\"vascular elasticity\"]",
            exampleSentence = "Arteriosclerosis reduces the flexibility of blood vessel walls.",
            exampleTranslation = "Arterioskleroz, kan damarı duvarlarının esnekliğini azaltır.", category = "fen", difficulty = 3, examYear = "2019"),
        Word(word = "assimilation", turkishMeaning = "asimilasyon, özümseme", partOfSpeech = "noun",
            synonyms = "[\"absorption\",\"incorporation\",\"integration\"]", antonyms = "[\"rejection\",\"excretion\",\"expulsion\"]",
            exampleSentence = "Plants use assimilation to incorporate nitrogen into organic compounds.",
            exampleTranslation = "Bitkiler, azotu organik bileşiklere katmak için asimilasyonu kullanır.", category = "fen", difficulty = 3, examYear = "2021"),
        Word(word = "atmosphere", turkishMeaning = "atmosfer, hava katmanı", partOfSpeech = "noun",
            synonyms = "[\"air layer\",\"gaseous envelope\",\"troposphere\"]", antonyms = "[\"vacuum\",\"outer space\",\"void\"]",
            exampleSentence = "The atmosphere protects life on Earth from harmful solar radiation.",
            exampleTranslation = "Atmosfer, Dünya'daki yaşamı zararlı güneş radyasyonundan korur.", category = "fen", difficulty = 2, examYear = "2017"),
        Word(word = "autotroph", turkishMeaning = "ototrof, kendi kendine beslenebilen", partOfSpeech = "noun",
            synonyms = "[\"producer\",\"primary producer\",\"self-feeder\"]", antonyms = "[\"heterotroph\",\"consumer\",\"decomposer\"]",
            exampleSentence = "Green plants are autotrophs that produce food via photosynthesis.",
            exampleTranslation = "Yeşil bitkiler fotosentez yoluyla besin üreten ototroflardır.", category = "fen", difficulty = 3, examYear = "2020"),
        Word(word = "biomass", turkishMeaning = "biyokütle", partOfSpeech = "noun",
            synonyms = "[\"organic matter\",\"biological material\",\"living mass\"]", antonyms = "[\"fossil fuel\",\"inorganic material\"]",
            exampleSentence = "Biomass energy is derived from organic materials like wood.",
            exampleTranslation = "Biyokütle enerjisi, ahşap gibi organik maddelerden elde edilir.", category = "fen", difficulty = 2, examYear = "2018"),
        Word(word = "capillary", turkishMeaning = "kılcal damar", partOfSpeech = "noun",
            synonyms = "[\"small vessel\",\"microvessel\",\"capillary tube\"]", antonyms = "[\"artery\",\"main vessel\",\"vein\"]",
            exampleSentence = "Capillaries facilitate the exchange of nutrients between blood and tissues.",
            exampleTranslation = "Kılcal damarlar, kan ve dokular arasındaki besin alışverişini kolaylaştırır.", category = "fen", difficulty = 2, examYear = "2021"),
        Word(word = "carcinogen", turkishMeaning = "kanserojen, kanser etkeni", partOfSpeech = "noun",
            synonyms = "[\"cancer-causing agent\",\"mutagen\",\"tumor promoter\"]", antonyms = "[\"anticarcinogen\",\"protective agent\"]",
            exampleSentence = "Tobacco smoke contains multiple carcinogens linked to lung cancer.",
            exampleTranslation = "Tütün dumanı akciğer kanseriyle bağlantılı birden fazla kanserojen içerir.", category = "fen", difficulty = 2, examYear = "2019"),
        Word(word = "chlorophyll", turkishMeaning = "klorofil", partOfSpeech = "noun",
            synonyms = "[\"green pigment\",\"photosynthetic pigment\",\"plant pigment\"]", antonyms = "[\"carotenoid\",\"anthocyanin\"]",
            exampleSentence = "Chlorophyll absorbs blue and red light for photosynthesis.",
            exampleTranslation = "Klorofil, fotosentez için mavi ve kırmızı ışığı emer.", category = "fen", difficulty = 2, examYear = "2017"),
        Word(word = "coagulation", turkishMeaning = "pıhtılaşma, koagülasyon", partOfSpeech = "noun",
            synonyms = "[\"clotting\",\"solidification\",\"curdling\"]", antonyms = "[\"dissolution\",\"liquefaction\",\"anticoagulation\"]",
            exampleSentence = "Blood coagulation stops bleeding when blood vessels are damaged.",
            exampleTranslation = "Kan pıhtılaşması, kan damarları hasar gördüğünde kanamayı durdurur.", category = "fen", difficulty = 3, examYear = "2022"),
        Word(word = "conductivity", turkishMeaning = "iletkenlik", partOfSpeech = "noun",
            synonyms = "[\"electrical conductance\",\"thermal conductivity\"]", antonyms = "[\"resistance\",\"insulation\",\"impedance\"]",
            exampleSentence = "Copper has high electrical conductivity, making it ideal for wiring.",
            exampleTranslation = "Bakırın yüksek elektrik iletkenliği onu kablolama için ideal kılar.", category = "fen", difficulty = 2, examYear = "2020"),
        Word(word = "convergent", turkishMeaning = "yakınsak, bir araya gelen", partOfSpeech = "adj",
            synonyms = "[\"merging\",\"unifying\",\"concentrating\"]", antonyms = "[\"divergent\",\"spreading\",\"dispersing\"]",
            exampleSentence = "Convergent evolution produces similar traits in unrelated species.",
            exampleTranslation = "Yakınsak evrim, ilgisiz türlerde benzer özellikler üretir.", category = "fen", difficulty = 3, examYear = "2021"),
        Word(word = "decomposition", turkishMeaning = "ayrışma, çürüme", partOfSpeech = "noun",
            synonyms = "[\"decay\",\"breakdown\",\"putrefaction\"]", antonyms = "[\"synthesis\",\"formation\",\"construction\"]",
            exampleSentence = "Decomposition of dead organisms recycles nutrients back into the ecosystem.",
            exampleTranslation = "Ölü organizmaların ayrışması besinleri ekosisteme geri kazandırır.", category = "fen", difficulty = 2, examYear = "2018"),
        Word(word = "dilute", turkishMeaning = "seyreltmek, zayıflatmak", partOfSpeech = "verb",
            synonyms = "[\"thin\",\"weaken\",\"reduce concentration\"]", antonyms = "[\"concentrate\",\"strengthen\",\"thicken\"]",
            exampleSentence = "The acid was diluted with water to reduce its concentration.",
            exampleTranslation = "Asit, konsantrasyonunu azaltmak için suyla seyreltildi.", category = "fen", difficulty = 2, examYear = "2019"),
        Word(word = "divergent", turkishMeaning = "ıraksak, ayrışan", partOfSpeech = "adj",
            synonyms = "[\"different\",\"branching\",\"varying\"]", antonyms = "[\"convergent\",\"similar\",\"unified\"]",
            exampleSentence = "Divergent evolution leads to different species from a common ancestor.",
            exampleTranslation = "Iraksak evrim, ortak bir atadan farklı türlerin oluşmasına yol açar.", category = "fen", difficulty = 3, examYear = "2022"),
        Word(word = "dominant", turkishMeaning = "baskın, dominant", partOfSpeech = "adj",
            synonyms = "[\"prevailing\",\"controlling\",\"superior\"]", antonyms = "[\"recessive\",\"subordinate\",\"weak\"]",
            exampleSentence = "The dominant allele masks the effect of the recessive allele.",
            exampleTranslation = "Dominant alel, resesif alelin etkisini gizler.", category = "fen", difficulty = 2, examYear = "2020"),
        Word(word = "dormant", turkishMeaning = "uyuyan, hareketsiz, latent", partOfSpeech = "adj",
            synonyms = "[\"inactive\",\"latent\",\"quiescent\"]", antonyms = "[\"active\",\"awake\",\"germinating\"]",
            exampleSentence = "Seeds remain dormant until environmental conditions become favorable.",
            exampleTranslation = "Tohumlar, çevre koşulları uygun hale gelene kadar uyku halinde kalır.", category = "fen", difficulty = 2, examYear = "2018"),
        Word(word = "effluent", turkishMeaning = "atık su, deşarj", partOfSpeech = "noun",
            synonyms = "[\"wastewater\",\"discharge\",\"outflow\"]", antonyms = "[\"clean water\",\"influent\",\"purified water\"]",
            exampleSentence = "Industrial effluent must be treated before release into rivers.",
            exampleTranslation = "Endüstriyel atık su, nehirlere bırakılmadan önce arıtılmalıdır.", category = "fen", difficulty = 3, examYear = "2021"),
        Word(word = "elasticity", turkishMeaning = "esneklik, elastikiyet", partOfSpeech = "noun",
            synonyms = "[\"flexibility\",\"stretchability\",\"resilience\"]", antonyms = "[\"rigidity\",\"stiffness\",\"inelasticity\"]",
            exampleSentence = "Arterial elasticity allows blood vessels to expand with each heartbeat.",
            exampleTranslation = "Arteriyel esneklik, kan damarlarının her kalp atışıyla genişlemesine izin verir.", category = "fen", difficulty = 2, examYear = "2019"),
        Word(word = "endocrine", turkishMeaning = "endokrin, iç salgı", partOfSpeech = "adj",
            synonyms = "[\"hormonal\",\"glandular\",\"secretory\"]", antonyms = "[\"exocrine\",\"external secretion\"]",
            exampleSentence = "The endocrine system regulates body functions through hormones.",
            exampleTranslation = "Endokrin sistem, hormonlar aracılığıyla vücut işlevlerini düzenler.", category = "fen", difficulty = 3, examYear = "2020"),
        Word(word = "entropy", turkishMeaning = "entropi, düzensizlik", partOfSpeech = "noun",
            synonyms = "[\"disorder\",\"randomness\",\"degradation\"]", antonyms = "[\"order\",\"organization\",\"low entropy\"]",
            exampleSentence = "According to thermodynamics, entropy always increases in isolated systems.",
            exampleTranslation = "Termodinamiğe göre entropi, izole sistemlerde her zaman artar.", category = "fen", difficulty = 3, examYear = "2022"),
        Word(word = "exponential", turkishMeaning = "üstel, katlanarak artan", partOfSpeech = "adj",
            synonyms = "[\"rapid\",\"geometric\",\"accelerating\"]", antonyms = "[\"linear\",\"constant\",\"gradual\"]",
            exampleSentence = "Bacterial population grows at an exponential rate.",
            exampleTranslation = "Bakteri popülasyonu üstel bir hızda büyür.", category = "fen", difficulty = 2, examYear = "2018"),
        Word(word = "fission", turkishMeaning = "fisyon, bölünme", partOfSpeech = "noun",
            synonyms = "[\"splitting\",\"division\",\"fragmentation\"]", antonyms = "[\"fusion\",\"combination\",\"merger\"]",
            exampleSentence = "Nuclear fission releases enormous amounts of energy.",
            exampleTranslation = "Nükleer fisyon çok büyük miktarda enerji açığa çıkarır.", category = "fen", difficulty = 2, examYear = "2019"),
        Word(word = "fusion", turkishMeaning = "füzyon, birleşme", partOfSpeech = "noun",
            synonyms = "[\"merging\",\"union\",\"combination\"]", antonyms = "[\"fission\",\"splitting\",\"separation\"]",
            exampleSentence = "Nuclear fusion powers the sun by combining hydrogen atoms.",
            exampleTranslation = "Nükleer füzyon, hidrojen atomlarını birleştirerek güneşe güç sağlar.", category = "fen", difficulty = 2, examYear = "2021"),
        Word(word = "gamete", turkishMeaning = "gamet, üreme hücresi", partOfSpeech = "noun",
            synonyms = "[\"sex cell\",\"reproductive cell\",\"germ cell\"]", antonyms = "[\"somatic cell\",\"body cell\"]",
            exampleSentence = "Gametes are haploid cells produced by meiosis.",
            exampleTranslation = "Gametler, mayoz yoluyla üretilen haploid hücrelerdir.", category = "fen", difficulty = 2, examYear = "2017"),
        Word(word = "genome", turkishMeaning = "genom, tam genetik yapı", partOfSpeech = "noun",
            synonyms = "[\"genetic code\",\"DNA blueprint\",\"complete gene set\"]", antonyms = "[\"partial sequence\",\"single gene\"]",
            exampleSentence = "The human genome contains approximately 3 billion base pairs.",
            exampleTranslation = "İnsan genomu yaklaşık 3 milyar baz çifti içerir.", category = "fen", difficulty = 2, examYear = "2020"),
        Word(word = "glucagon", turkishMeaning = "glukagon", partOfSpeech = "noun",
            synonyms = "[\"glucose-raising hormone\",\"pancreatic hormone\"]", antonyms = "[\"insulin\",\"glucose-lowering hormone\"]",
            exampleSentence = "Glucagon raises blood glucose levels when they drop too low.",
            exampleTranslation = "Glukagon, kan glukoz seviyeleri çok düştüğünde bunları yükseltir.", category = "fen", difficulty = 3, examYear = "2022"),
        Word(word = "halogen", turkishMeaning = "halojen", partOfSpeech = "noun",
            synonyms = "[\"reactive nonmetal\",\"Group 17 element\"]", antonyms = "[\"noble gas\",\"inert element\"]",
            exampleSentence = "Chlorine is a halogen used to disinfect drinking water.",
            exampleTranslation = "Klor, içme suyunu dezenfekte etmek için kullanılan bir halojendir.", category = "fen", difficulty = 3, examYear = "2019"),
        Word(word = "hormesis", turkishMeaning = "hormezis (düşük dozda yararlı etki)", partOfSpeech = "noun",
            synonyms = "[\"biphasic dose response\",\"adaptive response\"]", antonyms = "[\"linear toxicity\",\"monotonic response\"]",
            exampleSentence = "Hormesis suggests that low levels of stress can strengthen cells.",
            exampleTranslation = "Hormezis, düşük düzeydeki stresin hücreleri güçlendirebileceğini ileri sürer.", category = "fen", difficulty = 3, examYear = "2021"),
        Word(word = "hydrolysis", turkishMeaning = "hidroliz", partOfSpeech = "noun",
            synonyms = "[\"water splitting\",\"decomposition by water\"]", antonyms = "[\"dehydration synthesis\",\"condensation\"]",
            exampleSentence = "Hydrolysis breaks down complex carbohydrates into simple sugars.",
            exampleTranslation = "Hidroliz, kompleks karbonhidratları basit şekerlere ayrıştırır.", category = "fen", difficulty = 3, examYear = "2020"),
        Word(word = "hypothesis testing", turkishMeaning = "hipotez testi", partOfSpeech = "noun",
            synonyms = "[\"statistical test\",\"significance test\",\"null hypothesis test\"]", antonyms = "[\"assumption\",\"untested claim\"]",
            exampleSentence = "Hypothesis testing determines whether data supports a claim.",
            exampleTranslation = "Hipotez testi, verilerin bir iddiayi destekleyip desteklemediğini belirler.", category = "fen", difficulty = 3, examYear = "2022"),
        Word(word = "immune", turkishMeaning = "bağışık, immün", partOfSpeech = "adj",
            synonyms = "[\"resistant\",\"protected\",\"insusceptible\"]", antonyms = "[\"susceptible\",\"vulnerable\",\"exposed\"]",
            exampleSentence = "Vaccinated individuals are immune to many infectious diseases.",
            exampleTranslation = "Aşılı bireyler pek çok bulaşıcı hastalığa karşı bağışıktır.", category = "fen", difficulty = 2, examYear = "2018"),
        Word(word = "inorganic", turkishMeaning = "inorganik, cansız kökenli", partOfSpeech = "adj",
            synonyms = "[\"non-carbon-based\",\"mineral\",\"abiotic\"]", antonyms = "[\"organic\",\"carbon-based\",\"biological\"]",
            exampleSentence = "Inorganic compounds such as salts are essential for cellular function.",
            exampleTranslation = "Tuzlar gibi inorganik bileşikler hücresel işlevler için gereklidir.", category = "fen", difficulty = 2, examYear = "2019"),
        Word(word = "isoenzyme", turkishMeaning = "izoenzim", partOfSpeech = "noun",
            synonyms = "[\"isozyme\",\"enzyme variant\"]", antonyms = "[\"single enzyme\",\"uniform catalyst\"]",
            exampleSentence = "Isoenzymes catalyze the same reaction but differ in molecular structure.",
            exampleTranslation = "İzoenzimler aynı reaksiyonu katalize eder ancak moleküler yapıları farklıdır.", category = "fen", difficulty = 3, examYear = "2021"),
        Word(word = "isotope", turkishMeaning = "izotop", partOfSpeech = "noun",
            synonyms = "[\"atomic variant\",\"nuclide\",\"atomic form\"]", antonyms = "[\"element\",\"single atom type\"]",
            exampleSentence = "Carbon-14 is a radioactive isotope used in carbon dating.",
            exampleTranslation = "Karbon-14, karbon tarihlemesinde kullanılan radyoaktif bir izotoptur.", category = "fen", difficulty = 3, examYear = "2022"),
        Word(word = "kinetic energy", turkishMeaning = "kinetik enerji", partOfSpeech = "noun",
            synonyms = "[\"motion energy\",\"dynamic energy\",\"energy of movement\"]", antonyms = "[\"potential energy\",\"stored energy\",\"rest energy\"]",
            exampleSentence = "A moving ball has kinetic energy proportional to its speed.",
            exampleTranslation = "Hareket eden bir topun kinetik enerjisi hızıyla orantılıdır.", category = "fen", difficulty = 2, examYear = "2017"),
        Word(word = "lumen", turkishMeaning = "lümen, iç boşluk", partOfSpeech = "noun",
            synonyms = "[\"inner cavity\",\"hollow space\",\"channel\"]", antonyms = "[\"wall\",\"solid structure\",\"exterior\"]",
            exampleSentence = "Narrowing of the arterial lumen reduces blood flow.",
            exampleTranslation = "Arteriyel lümenin daralması kan akışını azaltır.", category = "fen", difficulty = 3, examYear = "2020"),
        Word(word = "macrophage", turkishMeaning = "makrofaj", partOfSpeech = "noun",
            synonyms = "[\"phagocyte\",\"immune cell\",\"monocyte\"]", antonyms = "[\"pathogen\",\"bacteria\",\"antigen\"]",
            exampleSentence = "Macrophages engulf and destroy pathogens in the bloodstream.",
            exampleTranslation = "Makrofajlar, kan dolaşımındaki patojenleri yutar ve yok eder.", category = "fen", difficulty = 3, examYear = "2021"),
        Word(word = "meiosis", turkishMeaning = "mayoz (üreme hücresi bölünmesi)", partOfSpeech = "noun",
            synonyms = "[\"reduction division\",\"sexual cell division\"]", antonyms = "[\"mitosis\",\"somatic division\"]",
            exampleSentence = "Meiosis produces four haploid gamete cells from one diploid cell.",
            exampleTranslation = "Mayoz, bir diploid hücreden dört haploid gamet hücresi üretir.", category = "fen", difficulty = 2, examYear = "2018"),
        Word(word = "mitochondria", turkishMeaning = "mitokondri", partOfSpeech = "noun",
            synonyms = "[\"powerhouse of the cell\",\"ATP generator\",\"organelle\"]", antonyms = "[\"chloroplast\",\"lysosome\"]",
            exampleSentence = "Mitochondria produce ATP through oxidative phosphorylation.",
            exampleTranslation = "Mitokondri, oksidatif fosforilasyon yoluyla ATP üretir.", category = "fen", difficulty = 2, examYear = "2019"),
        Word(word = "momentum", turkishMeaning = "momentum, hareket miktarı", partOfSpeech = "noun",
            synonyms = "[\"impetus\",\"inertia\",\"driving force\"]", antonyms = "[\"stillness\",\"rest\",\"deceleration\"]",
            exampleSentence = "Conservation of momentum applies in collisions between objects.",
            exampleTranslation = "Momentumun korunumu, nesneler arasındaki çarpışmalarda geçerlidir.", category = "fen", difficulty = 2, examYear = "2020"),
        Word(word = "nucleotide", turkishMeaning = "nükleotid", partOfSpeech = "noun",
            synonyms = "[\"DNA building block\",\"monomer\",\"base pair unit\"]", antonyms = "[\"amino acid\",\"fatty acid\"]",
            exampleSentence = "A nucleotide consists of a sugar, phosphate, and a nitrogenous base.",
            exampleTranslation = "Bir nükleotid şeker, fosfat ve azotlu bir bazdan oluşur.", category = "fen", difficulty = 3, examYear = "2022"),
        Word(word = "organic", turkishMeaning = "organik, karbonlu", partOfSpeech = "adj",
            synonyms = "[\"carbon-based\",\"biological\",\"natural\"]", antonyms = "[\"inorganic\",\"synthetic\",\"mineral\"]",
            exampleSentence = "Organic molecules always contain carbon and hydrogen.",
            exampleTranslation = "Organik moleküller her zaman karbon ve hidrojen içerir.", category = "fen", difficulty = 2, examYear = "2017"),
        Word(word = "osmotic pressure", turkishMeaning = "ozmotik basınç", partOfSpeech = "noun",
            synonyms = "[\"osmotic force\",\"water potential\"]", antonyms = "[\"isotonic pressure\",\"zero osmosis\"]",
            exampleSentence = "High osmotic pressure causes water to move into concentrated solutions.",
            exampleTranslation = "Yüksek ozmotik basınç, suyun konsantre çözeltilere doğru hareket etmesine neden olur.", category = "fen", difficulty = 3, examYear = "2021"),
        Word(word = "parasite", turkishMeaning = "parazit", partOfSpeech = "noun",
            synonyms = "[\"ectoparasite\",\"endoparasite\",\"freeloader\"]", antonyms = "[\"symbiont\",\"mutualist\",\"host\"]",
            exampleSentence = "A parasite benefits at the expense of its host organism.",
            exampleTranslation = "Bir parazit, konak organizmayı zarara uğratarak fayda sağlar.", category = "fen", difficulty = 2, examYear = "2018"),
        Word(word = "pathology", turkishMeaning = "patoloji, hastalık bilimi", partOfSpeech = "noun",
            synonyms = "[\"disease study\",\"medical science\",\"etiology\"]", antonyms = "[\"health\",\"physiology\",\"wellness\"]",
            exampleSentence = "Pathology examines tissue samples to diagnose diseases.",
            exampleTranslation = "Patoloji, hastalıkları teşhis etmek için doku örneklerini inceler.", category = "fen", difficulty = 2, examYear = "2020"),
        Word(word = "photon", turkishMeaning = "foton, ışık parçacığı", partOfSpeech = "noun",
            synonyms = "[\"light particle\",\"quantum\",\"energy packet\"]", antonyms = "[\"electron\",\"proton\",\"matter\"]",
            exampleSentence = "A photon is the basic unit of light and electromagnetic radiation.",
            exampleTranslation = "Foton, ışığın ve elektromanyetik radyasyonun temel birimidir.", category = "fen", difficulty = 3, examYear = "2022"),
        Word(word = "physiological", turkishMeaning = "fizyolojik", partOfSpeech = "adj",
            synonyms = "[\"biological\",\"bodily\",\"functional\"]", antonyms = "[\"pathological\",\"abnormal\",\"diseased\"]",
            exampleSentence = "Sweating is a physiological response to increased body temperature.",
            exampleTranslation = "Terleme, artan vücut sıcaklığına verilen fizyolojik bir yanıttır.", category = "fen", difficulty = 2, examYear = "2019"),
        Word(word = "plasma", turkishMeaning = "plazma (kan sıvısı / maddenin dördüncü hali)", partOfSpeech = "noun",
            synonyms = "[\"blood fluid\",\"serum\",\"ionized gas\"]", antonyms = "[\"solid\",\"blood cell\",\"formed element\"]",
            exampleSentence = "Blood plasma carries nutrients and hormones throughout the body.",
            exampleTranslation = "Kan plazması, besinleri ve hormonları vücut boyunca taşır.", category = "fen", difficulty = 2, examYear = "2018"),
        Word(word = "predation", turkishMeaning = "yırtıcılık, avlanma", partOfSpeech = "noun",
            synonyms = "[\"hunting\",\"prey-predator relationship\",\"carnivory\"]", antonyms = "[\"mutualism\",\"symbiosis\",\"herbivory\"]",
            exampleSentence = "Predation is a key factor in regulating population size.",
            exampleTranslation = "Yırtıcılık, popülasyon büyüklüğünün düzenlenmesinde temel bir faktördür.", category = "fen", difficulty = 2, examYear = "2021"),
        Word(word = "prokaryote", turkishMeaning = "prokaryot (çekirdeksiz hücre)", partOfSpeech = "noun",
            synonyms = "[\"bacteria\",\"archaea\",\"simple cell\"]", antonyms = "[\"eukaryote\",\"nucleated cell\",\"complex cell\"]",
            exampleSentence = "Prokaryotes lack a membrane-bound nucleus.",
            exampleTranslation = "Prokaryotlar, zarla çevrili bir çekirdeğe sahip değildir.", category = "fen", difficulty = 3, examYear = "2020"),
        Word(word = "proton", turkishMeaning = "proton", partOfSpeech = "noun",
            synonyms = "[\"positive charge\",\"hydrogen nucleus\",\"baryon\"]", antonyms = "[\"electron\",\"antiproton\",\"neutron\"]",
            exampleSentence = "The number of protons in an atom defines its element.",
            exampleTranslation = "Bir atomdaki proton sayısı, onun elementini tanımlar.", category = "fen", difficulty = 2, examYear = "2017"),
        Word(word = "recessive", turkishMeaning = "resesif, çekinik", partOfSpeech = "adj",
            synonyms = "[\"hidden\",\"masked\",\"non-dominant\"]", antonyms = "[\"dominant\",\"expressed\",\"manifested\"]",
            exampleSentence = "Cystic fibrosis is caused by a recessive genetic mutation.",
            exampleTranslation = "Kistik fibrozis, resesif bir genetik mutasyondan kaynaklanır.", category = "fen", difficulty = 2, examYear = "2019"),
        Word(word = "refraction", turkishMeaning = "kırılma (ışık)", partOfSpeech = "noun",
            synonyms = "[\"bending of light\",\"light deflection\"]", antonyms = "[\"reflection\",\"straight propagation\"]",
            exampleSentence = "Refraction of light creates the illusion of a bent straw in water.",
            exampleTranslation = "Işığın kırılması, suda bükülmüş bir saman görüntüsü yaratır.", category = "fen", difficulty = 2, examYear = "2020"),
        Word(word = "respiration", turkishMeaning = "solunum, hücresel solunum", partOfSpeech = "noun",
            synonyms = "[\"breathing\",\"cellular respiration\",\"oxidative metabolism\"]", antonyms = "[\"photosynthesis\",\"anabolism\"]",
            exampleSentence = "Cellular respiration converts glucose into ATP and carbon dioxide.",
            exampleTranslation = "Hücresel solunum, glikozu ATP ve karbondioksite dönüştürür.", category = "fen", difficulty = 2, examYear = "2017"),
        Word(word = "ribosome", turkishMeaning = "ribozom", partOfSpeech = "noun",
            synonyms = "[\"protein factory\",\"mRNA translator\",\"organelle\"]", antonyms = "[\"nucleus\",\"lysosome\"]",
            exampleSentence = "Ribosomes translate mRNA sequences into polypeptide chains.",
            exampleTranslation = "Ribozomlar, mRNA dizilerini polipeptit zincirlerine çevirir.", category = "fen", difficulty = 2, examYear = "2021"),
        Word(word = "salinity", turkishMeaning = "tuzluluk, tuz konsantrasyonu", partOfSpeech = "noun",
            synonyms = "[\"saltiness\",\"salt content\",\"sodium concentration\"]", antonyms = "[\"freshness\",\"low salinity\",\"dilution\"]",
            exampleSentence = "High salinity in ocean water prevents freshwater fish from surviving.",
            exampleTranslation = "Okyanus suyundaki yüksek tuzluluk, tatlı su balıklarının hayatta kalmasını engeller.", category = "fen", difficulty = 2, examYear = "2018"),
        Word(word = "selective pressure", turkishMeaning = "seçilim baskısı", partOfSpeech = "noun",
            synonyms = "[\"natural selection force\",\"evolutionary pressure\"]", antonyms = "[\"random drift\",\"neutral evolution\"]",
            exampleSentence = "Antibiotic use creates selective pressure for resistant bacteria.",
            exampleTranslation = "Antibiyotik kullanımı dirençli bakteriler üzerinde seçilim baskısı oluşturur.", category = "fen", difficulty = 3, examYear = "2022"),
        Word(word = "solvent", turkishMeaning = "çözücü", partOfSpeech = "noun",
            synonyms = "[\"dissolving agent\",\"medium\",\"liquid medium\"]", antonyms = "[\"solute\",\"precipitate\",\"insoluble substance\"]",
            exampleSentence = "Water is often called the universal solvent.",
            exampleTranslation = "Su genellikle evrensel çözücü olarak adlandırılır.", category = "fen", difficulty = 2, examYear = "2019"),
        Word(word = "speciation", turkishMeaning = "tür oluşumu, türleşme", partOfSpeech = "noun",
            synonyms = "[\"new species formation\",\"divergence\",\"evolutionary branching\"]", antonyms = "[\"extinction\",\"hybridization\",\"convergence\"]",
            exampleSentence = "Geographic isolation is a common cause of speciation.",
            exampleTranslation = "Coğrafi izolasyon, türleşmenin yaygın bir nedenidir.", category = "fen", difficulty = 3, examYear = "2021"),
        Word(word = "surface tension", turkishMeaning = "yüzey gerilimi", partOfSpeech = "noun",
            synonyms = "[\"cohesive force\",\"interfacial tension\"]", antonyms = "[\"low surface energy\",\"surfactant effect\"]",
            exampleSentence = "Surface tension allows water striders to walk on water.",
            exampleTranslation = "Yüzey gerilimi, su üzerinde yürüyen böceklerin bu işi yapmasına izin verir.", category = "fen", difficulty = 2, examYear = "2020"),
        Word(word = "symbiosis", turkishMeaning = "simbiyoz, ortak yaşam", partOfSpeech = "noun",
            synonyms = "[\"mutualism\",\"commensalism\",\"coexistence\"]", antonyms = "[\"competition\",\"parasitism\",\"predation\"]",
            exampleSentence = "Lichens are examples of symbiosis between fungi and algae.",
            exampleTranslation = "Likenler, mantar ve yosun arasındaki simbiyozun örnekleridir.", category = "fen", difficulty = 2, examYear = "2018"),
        Word(word = "thermal", turkishMeaning = "termal, ısıyla ilgili", partOfSpeech = "adj",
            synonyms = "[\"heat-related\",\"caloric\",\"thermodynamic\"]", antonyms = "[\"cold\",\"non-thermal\",\"cryogenic\"]",
            exampleSentence = "Thermal energy is transferred from hot to cold objects.",
            exampleTranslation = "Isı enerjisi sıcak nesnelerden soğuk nesnelere aktarılır.", category = "fen", difficulty = 2, examYear = "2017"),
        Word(word = "transpiration", turkishMeaning = "terleme (bitkisel), transpirasyon", partOfSpeech = "noun",
            synonyms = "[\"water loss\",\"evapotranspiration\",\"leaf evaporation\"]", antonyms = "[\"water absorption\",\"root uptake\"]",
            exampleSentence = "Transpiration cools plants and drives water absorption from roots.",
            exampleTranslation = "Transpirasyon bitkileri serinletir ve köklerden su emilimini sağlar.", category = "fen", difficulty = 2, examYear = "2021"),
        Word(word = "tropism", turkishMeaning = "tropizm (yönelim)", partOfSpeech = "noun",
            synonyms = "[\"directional growth\",\"movement response\",\"orientation\"]", antonyms = "[\"random growth\",\"non-directional movement\"]",
            exampleSentence = "Phototropism causes plants to grow toward light.",
            exampleTranslation = "Fototropizm, bitkilerin ışığa doğru büyümesine neden olur.", category = "fen", difficulty = 3, examYear = "2022"),
        Word(word = "valence", turkishMeaning = "valans, bağlanma kapasitesi", partOfSpeech = "noun",
            synonyms = "[\"combining capacity\",\"bonding number\",\"oxidation state\"]", antonyms = "[\"inert\",\"zero valence\"]",
            exampleSentence = "Oxygen has a valence of 2, forming two covalent bonds.",
            exampleTranslation = "Oksijenin valansı 2'dir ve iki kovalent bağ oluşturur.", category = "fen", difficulty = 3, examYear = "2019"),
        Word(word = "vector", turkishMeaning = "vektör, taşıyıcı", partOfSpeech = "noun",
            synonyms = "[\"carrier\",\"transmitter\",\"direction and magnitude\"]", antonyms = "[\"scalar\",\"non-directional\",\"magnitude only\"]",
            exampleSentence = "Mosquitoes act as vectors for malaria and dengue fever.",
            exampleTranslation = "Sivrisinekler, sıtma ve dang humması için vektör görevi görür.", category = "fen", difficulty = 2, examYear = "2020"),
        Word(word = "zygote", turkishMeaning = "zigot, döllenmiş yumurta", partOfSpeech = "noun",
            synonyms = "[\"fertilized egg\",\"diploid cell\",\"early embryo\"]", antonyms = "[\"gamete\",\"haploid cell\",\"sperm\"]",
            exampleSentence = "A zygote forms when a sperm fertilizes an egg cell.",
            exampleTranslation = "Bir sperm yumurta hücresini döllediğinde zigot oluşur.", category = "fen", difficulty = 2, examYear = "2018")
    )
}
